### PR TITLE
Update dependencies 2019 08 05

### PR DESCRIPTION
**Pull request by schmir-at-bb**
one of the tests fails at the moment

### CODE REVIEW

**Comment by schmir-at-bb** [comment]
The failing test seems to be problem introduced here: https://github.com/ethereum/py-evm/commit/4397ef90e35010b64f83e34ec57b911918df575b

**Comment by schmir-at-bb** [comment]
My suggestion would be to mark the failing test with xfail and open an issue here and in the py-evm repo.
The alternative would be to downgrade py-evm and eth-tester.

**Comment by cducrest** [comment]
Have you tried giving the transaction for self-destruct a defined amount of gas (like 30k or 40k)?
As far as I remember, when web3 fails to properly estimate the gas for a transaction it uses the block gas limit, so if it also fails to evaluate the block gas limit, error occurs.

**Comment by schmir-at-bb** [comment]
> Have you tried giving the transaction for self-destruct a defined amount of gas (like 30k or 40k)?

no

**Comment by schmir-at-bb** [comment]
> My suggestion would be to mark the failing test with xfail and open an issue here and in the py-evm repo.

Does anyone have objections against that? @berndbohmeier @cducrest

**Comment by cducrest** [comment]
No objection

**Comment by berndbohmeier** [comment]
Yes, open an issue first, and then mark the test with xfail with a comment pointing to the issue.

**Pull request merged**
